runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: static/index.html
  upload: static/index.html
  expiration: "15m"

- url: /(.*\.(html))$
  static_files: static/\1
  upload: static/.*\.(html)$

- url: /css
  static_dir: static/css